# Use an official Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /PromoMailerPipeline

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Command to run the application
CMD ["python", "autopromomailer.py"]
