services:
  pythonapp:
    build: ./pythonapp/
    command: sh -c "sleep 10s ; python3 ./autopromomailer.py"
    depends_on:
      - mysql
  mysql:
    build: ./mysql/
    restart: always
    environment:
      - MYSQL_DATABASE: 'emp'
      - MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - 3306:3306